### ISSUE TITLE
AttributeError: 'module' object has no attribute 'LabelMap'

### ISSUE THREAD

**Issue by kihyunU** [xiaohaoChen/rrc_detection#52]
I want to test with ./example/car/rrc_test.py
I got error message 
Traceback (most recent call last):
  File "examples/car/rrc_test.py", line 35, in <module>
    voc_labelmap = caffe_pb2.LabelMap()
AttributeError: 'module' object has no attribute 'LabelMap'

I tried re-installing caffe, pycaffe
However, I have same error.
Can you help me?

**Comment by joonjeon** [comment]
Hi! this is joonjeon.

Well, it seems like over a year has passed since this issue... :/
but just in case, I would like to share my experience hoping that others can have problem-free environment in testing the RRC.

As far as my experience is concerned, I suggest you use **exactly** the same version of Caffe and Numpy used by the original developers.

The code fails to compile in the latest versions of Numpy, perhaps because Numpy has **stopped supporting some functions and/or arguments** that had been mentioned as **'deprecated'**.
In addition, the build of Caffe framework used by the original developers is **NOT** the official release. There are several Caffe framework functions that are custom implemented (in C++) by the original RRC developers, which are not supported by any means in any of the official releases.
